#' Generate ARMA noise calibrated to a target signal-to-noise ratio
#'
#' Generates an ARMA noise series and adds it to a signal `x.state`, scaling
#' the innovation standard deviation so that the ratio of the smoothed signal
#' variance to the smoothed noise variance matches `lambda_target`.
#'
#' Coefficients can be supplied directly via `ar.coefs` and `ma.coefs`, or
#' auto-generated by supplying `order = c(p, q)`. Auto-generation uses the
#' PACF parameterisation: partial autocorrelations are drawn uniformly from
#' (-0.95, 0.95) and converted to coefficients via the Durbin-Levinson
#' recursion, which guarantees causality and invertibility by construction.
#'
#' @param x.state Numeric vector. The signal (trend) to add noise to.
#' @param h Integer. Moving-average window length used for SNR calibration.
#' @param ar.coefs Numeric vector. AR coefficients of the noise process.
#'   Defaults to `numeric(0)` (no AR component). Must yield a causal process
#'   (all roots of the AR polynomial outside the unit circle). Cannot be used
#'   together with `order`.
#' @param ma.coefs Numeric vector. MA coefficients of the noise process.
#'   Defaults to `numeric(0)` (no MA component). Must yield an invertible
#'   process (all roots of the MA polynomial outside the unit circle). Cannot
#'   be used together with `order`.
#' @param order Integer vector of length 2, `c(p, q)`. If supplied, AR and MA
#'   coefficients are auto-generated from a causal/invertible PACF
#'   parameterisation. Cannot be used together with explicit `ar.coefs` or
#'   `ma.coefs`.
#' @param lambda_target Numeric. Target signal-to-noise ratio (default 1).
#' @param s Integer or NULL. Window length for local variance estimation during
#'   calibration. If `NULL`, defaults to `2 * h`.
#' @param n_start Integer. Number of burn-in observations for `arima.sim`
#'   (default 100).
#' @param seed Integer or NULL. RNG seed for reproducibility. Applies to both
#'   coefficient auto-generation (if `order` is used) and noise simulation.
#'
#' @return A list with three sublists:
#'   \describe{
#'     \item{inputs}{`ar`, `ma`, `lambda_target`, `seed`.}
#'     \item{outputs}{`x` (signal), `noise`, `y` (observed = signal + noise),
#'       all as plain numeric vectors.}
#'     \item{diagnostics}{`sigma` (calibrated innovation SD),
#'       `noise_var_ratio` (empirical/theoretical smooth noise variance; should
#'       be near 1), `snr_local` (local SNR over the interior),
#'       `lv_signal`, `lv_noise` (local variances of smoothed signal and
#'       noise).}
#'   }
#'
#' @seealso [sim_noise_pair()], [sim_trends()]
#'
#' @export
sim_noise <- function(x.state,
                      h,
                      ar.coefs = numeric(0),
                      ma.coefs = numeric(0),
                      order = NULL,
                      lambda_target = 1,
                      s = NULL,
                      n_start = 100,
                      seed = NULL) {
  n <- length(x.state)
  if (is.null(s)) s <- 2 * h

  if (!is.null(seed)) set.seed(seed)

  # --- Coefficient resolution ---

  explicit_ar <- length(ar.coefs) > 0
  explicit_ma <- length(ma.coefs) > 0

  if (!is.null(order) && (explicit_ar || explicit_ma)) {
    stop("Supply either `order` for auto-generation or explicit `ar.coefs`/`ma.coefs`, not both.")
  }

  if (!is.null(order)) {
    if (length(order) != 2 || any(order < 0) || any(order != floor(order))) {
      stop("`order` must be a length-2 vector of non-negative integers: c(p, q).")
    }
    ar.coefs <- .pacf_to_arma_coefs(order[1])
    ma.coefs <- .pacf_to_arma_coefs(order[2])
    message(sprintf(
      "Auto-generated ARMA(%d,%d) coefficients via PACF parameterisation.", order[1], order[2]
    ))
  }

  # --- Causality / invertibility checks ---

  if (length(ar.coefs) > 0) {
    ar_roots <- Mod(polyroot(c(1, -ar.coefs)))
    if (any(ar_roots <= 1)) {
      stop(
        "AR coefficients do not yield a causal process: ",
        "all roots of the AR polynomial must have modulus > 1. ",
        sprintf("Smallest root modulus: %.4f", min(ar_roots))
      )
    }
  }

  if (length(ma.coefs) > 0) {
    ma_roots <- Mod(polyroot(c(1, ma.coefs)))
    if (any(ma_roots <= 1)) {
      stop(
        "MA coefficients do not yield an invertible process: ",
        "all roots of the MA polynomial must have modulus > 1. ",
        sprintf("Smallest root modulus: %.4f", min(ma_roots))
      )
    }
  }

  # --- Calibration ---

  max_lag <- s + h - 2L

  if (length(ar.coefs) == 0 && length(ma.coefs) == 0) {
    gamma_unit_ext <- c(1, rep(0, max_lag))
  } else {
    psi            <- stats::ARMAtoMA(ar = ar.coefs, ma = ma.coefs,
                                      lag.max = max(200L, max_lag))
    gamma0_unit    <- sum(c(1, psi[seq_len(min(length(psi), max(200L, max_lag)))])^2)
    gamma_unit_ext <- gamma0_unit *
      stats::ARMAacf(ar = ar.coefs, ma = ma.coefs, lag.max = max_lag)
  }

  d_vals <- seq.int(-(h - 1L), h - 1L)
  w_d    <- as.numeric(h - abs(d_vals))
  cov_e  <- vapply(seq.int(0L, s - 1L), function(k) {
    sum(w_d * gamma_unit_ext[abs(k + d_vals) + 1L]) / h^2
  }, numeric(1L))

  k_seq             <- seq_len(s - 1L)
  var_window_mean_e <- (s * cov_e[1L] + 2 * sum((s - k_seq) * cov_e[k_seq + 1L])) / s^2
  var_smooth_eff    <- (s / (s - 1L)) * (cov_e[1L] - var_window_mean_e)

  x_smooth     <- roll::roll_mean(x.state, width = h, min_obs = h)
  var_x_smooth <- mean(roll::roll_var(x_smooth, width = s, center = TRUE,
                                      min_obs = s),
                       na.rm = TRUE)

  sigma <- sqrt(var_x_smooth / (lambda_target * var_smooth_eff))

  # --- Simulation ---

  noise <- as.numeric(stats::arima.sim(
    model = list(order = c(length(ar.coefs), 0, length(ma.coefs)),
                 ar = ar.coefs, ma = ma.coefs),
    n = n,
    rand.gen = function(t) stats::rnorm(t, mean = 0, sd = sigma),
    n.start = n_start
  ))

  y <- x.state + noise

  # --- Diagnostics ---

  x_smooth_chk <- roll::roll_mean(x.state, width = h, min_obs = h)
  e_smooth     <- roll::roll_mean(noise,   width = h, min_obs = h)

  lv_signal <- roll::roll_var(x_smooth_chk, width = s, center = TRUE, min_obs = s)
  lv_noise  <- roll::roll_var(e_smooth,     width = s, center = TRUE, min_obs = s)

  interior <- (h + floor(s / 2)):(n - floor(s / 2))
  ok        <- !is.na(lv_signal[interior]) & !is.na(lv_noise[interior]) &
    lv_noise[interior] > 1e-5
  snr_local <- lv_signal[interior][ok] / lv_noise[interior][ok]

  noise_var_ratio <- mean(lv_noise[interior], na.rm = TRUE) /
    (sigma^2 * var_smooth_eff)

  mean_snr <- mean(lv_signal[interior][ok]) / mean(lv_noise[interior][ok])

  message(sprintf(
    "SNR target: %.2f | mean: %.2f (%+.1f%%) | noise var ratio (emp/theo): %.3f | n: %d",
    lambda_target,
    mean_snr, 100 * (mean_snr - lambda_target) / lambda_target,
    noise_var_ratio,
    length(snr_local)
  ))

  list(
    inputs = list(
      x             = as.numeric(x.state),
      ar            = ar.coefs,
      ma            = ma.coefs,
      lambda_target = lambda_target,
      seed          = seed
    ),
    outputs = list(
      sigma = sigma,
      noise = noise,
      y     = y
    ),
    diagnostics = list(
      mean_snr        = mean_snr,
      noise_var_ratio = noise_var_ratio,
      snr_local       = snr_local,
      lv_signal       = lv_signal,
      lv_noise        = lv_noise
    )
  )
}


#' Add calibrated ARMA noise to a pair of trend series
#'
#' Convenience wrapper around [sim_noise()] for use with output from
#' [sim_trends()]. Applies noise models to both series and returns the
#' observed series alongside high-level diagnostics.
#'
#' `lambda_target` and `order` can be supplied as a single value (shared across
#' both series) or as a length-2 vector / list (one per series). Seeds for the
#' two calls are derived independently from `seed` so that the two noise
#' processes are not identical.
#'
#' @param trends List returned by [sim_trends()], with elements `x1` and `x2`.
#' @param h Integer. MA window for SNR calibration (passed to [sim_noise()]).
#' @param lambda_target Numeric scalar or length-2 vector. Target SNR for each
#'   series. If scalar, the same target is used for both (default 1).
#' @param scale Numeric. Multiplicative scale applied to both trend series
#'   before adding noise (default 1).
#' @param ar.coefs Numeric vector. AR coefficients (see [sim_noise()]).
#' @param ma.coefs Numeric vector. MA coefficients (see [sim_noise()]).
#' @param order `c(p, q)` integer vector, or a list of two such vectors. If
#'   supplied, auto-generates ARMA coefficients independently for each series
#'   (see [sim_noise()]). Cannot be combined with `ar.coefs` / `ma.coefs`.
#' @param s Integer or NULL. Window for local variance estimation (see
#'   [sim_noise()]).
#' @param n_start Integer. Burn-in observations for `arima.sim` (default 100).
#' @param seed Integer or NULL. RNG seed for reproducibility. Seeds for the two
#'   series are derived as `seed` and `seed + 1` so their noise processes are
#'   independent.
#'
#' @return A list:
#'   \describe{
#'     \item{y1, y2}{Observed series (signal + noise), as plain numeric
#'       vectors.}
#'     \item{x1, x2}{Scaled trend series (i.e. `scale * trends$x1/x2`).}
#'     \item{noise}{List with `series1` and `series2`, each containing:
#'       `ar`, `ma` (coefficients used), `sigma` (innovation SD), `mean_snr`
#'       (mean local SNR), and `noise_var_ratio` (empirical / theoretical
#'       smooth noise variance; should be near 1).}
#'   }
#'
#' @seealso [sim_noise()], [sim_trends()]
#'
#' @export
sim_noise_pair <- function(trends,
                           h,
                           lambda_target = 1,
                           scale         = 1,
                           ar.coefs      = numeric(0),
                           ma.coefs      = numeric(0),
                           order         = NULL,
                           s             = NULL,
                           n_start       = 100,
                           seed          = NULL) {

  # --- Expand per-series arguments ---

  if (length(lambda_target) == 1L) {
    lambda_target <- c(lambda_target, lambda_target)
  } else if (length(lambda_target) != 2L) {
    stop("`lambda_target` must be a scalar or length-2 vector.")
  }

  if (is.null(order)) {
    order1 <- order2 <- NULL
  } else if (is.list(order)) {
    if (length(order) != 2L)
      stop("`order` as a list must have exactly 2 elements.")
    order1 <- order[[1]]
    order2 <- order[[2]]
  } else {
    order1 <- order2 <- order
  }

  seed1 <- if (!is.null(seed)) seed      else NULL
  seed2 <- if (!is.null(seed)) seed + 1L else NULL

  x1 <- scale * trends$x1
  x2 <- scale * trends$x2

  n1 <- sim_noise(x.state = x1, h = h, lambda_target = lambda_target[1],
                  ar.coefs = ar.coefs, ma.coefs = ma.coefs, order = order1,
                  s = s, n_start = n_start, seed = seed1)
  n2 <- sim_noise(x.state = x2, h = h, lambda_target = lambda_target[2],
                  ar.coefs = ar.coefs, ma.coefs = ma.coefs, order = order2,
                  s = s, n_start = n_start, seed = seed2)

  diag_slim <- function(nm) {
    list(
      ar              = nm$inputs$ar,
      ma              = nm$inputs$ma,
      sigma           = nm$outputs$sigma,
      mean_snr        = nm$diagnostics$mean_snr,
      noise_var_ratio = nm$diagnostics$noise_var_ratio
    )
  }

  list(
    y1    = n1$outputs$y,
    y2    = n2$outputs$y,
    x1    = x1,
    x2    = x2,
    noise = list(
      series1 = diag_slim(n1),
      series2 = diag_slim(n2)
    )
  )
}
